CREATE TABLE register(
  id INT PRIMARY KEY AUTO_INCREMENT,
  number VARCHAR(150) NOT NULL,
  classroom VARCHAR(150) NOT NULL,
  shift VARCHAR(150) NOT NULL,
  headquarters VARCHAR(150) NOT NULL,
  sec VARCHAR(150) NOT NULL,
  exp VARCHAR(150) NOT NULL,
  dni VARCHAR(20) NOT NULL,
  nameSurname VARCHAR(100) NOT NULL,
  school VARCHAR(150) NOT NULL DEFAULT "",
  plan VARCHAR(150) NOT NULL DEFAULT "",
  codOp1 VARCHAR(20) NOT NULL DEFAULT "",
  codOp2 VARCHAR(20) NOT NULL DEFAULT ""
);